spring:
    profiles:
        active:
        - dev
---
spring:
    profiles:dev
    appliction:
        name:microservicecloud-dev
---
spring:
    profiles:test
    appliction:
        name:microservicecloud-test
